### ISSUE TITLE
Always TimeoutException on Android

### ISSUE THREAD

**Issue by ghost** [telegram-s/telegram-api-old#23]
I'm developing on Android and i've tested my app on emulator and real device. At first i've used the last jar distributed, but after some timeout exception i've seen other issue and i've reverted to the v11 implementation.
Now i'm sending the code to my phone, switching datacenter and then sign in with phone, phone's hashcode and signkey but it always return me timeout exception.
I'm also following the guideline on the Telegram docs and it seems to be the good way, also the docs tell me that it should return error, but it will return me always timeout exception.
There's a way to get out of this? I'm getting mad, i don't know if i'm missing something or if the api are inconsistent.

**Comment by marchagele** [comment]
A lot of people have the same issue (me included), project maybe not continued anymore?
as ex3ndr does not respond since a lot of time.

**Comment by ghost** [comment]
So should we use the telegram ufficial application source code and understand how it work?

I'll reply with a modified Smiths song (https://www.youtube.com/watch?v=2ownZDWNIRs) :

«Frankly, Mr. ex3ndr, this project I've held
It pays my way, and it corrodes my soul
I want to leave, you will not miss me
I want to go down in git source code history»

**Comment by marchagele** [comment]
I think it would be the wise way.
Only problem I got is, I am not a Java developer. I am using it as a .NET Library ("converted" JAR,
packed with ikvm) - thats also why I am not able to getting to the point where it really fails.

**Comment by ghost** [comment]
po0kie as far as i concerned it's a timeout from the server so a erroneous request, but the code has not been updated from at least 3 months. Did anyone really can't get rid of this nasty error?

**Comment by marchagele** [comment]
And the response from Server, is there some more detailed information about the erroneous request?
(debugging info..?)

**Comment by ghost** [comment]
po0kie the response never arrive, it's a timeout.

**Comment by marchagele** [comment]
You are sure it is? Because to me it does not really take much time to throw the "Timeout".
It seems to me like the server deny the request directly, and the library just takes it like a "timeout" (wrong interpretation of the fault),  can it be?

**Comment by ghost** [comment]
I'll review it soon just to be sure.

**Comment by marchagele** [comment]
Ok! Hope you will put something here if you found some details about it :)

**Comment by jinfeei** [comment]
Same problem here I have? I tried running telegram-bot, but nothing works... Sigh...

Use test DC? (write test for test servers): test
Using test servers
Loading fresh DC list...completed.
Phone number for bot:+6012xxxxxxxx
Sending sms to phone +6012xxxxxxxx...
Exception in thread "main" org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:369)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:428)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:420)
    at com.gracker.telegram.Main.login(Main.java:386)
    at com.gracker.telegram.Main.main(Main.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by alexkvak** [comment]
see this solution for linux [#9](https://github.com/ex3ndr/telegram-api/issues/9#issuecomment-38175765)

**Comment by anttorval** [comment]
and for windows????

**Comment by Raakh** [comment]
Can you please send me compiled working code to my email ghayel@gmail.com? I shall be grateful to you
