### ISSUE TITLE
Getting Below Error While Trying To run ""gradle build"

### ISSUE THREAD

**Issue by prasenjeet86** [telegram-s/telegram-api-old#26]
- Exception is:
  org.gradle.api.GradleException: Could not determine the dependencies of task ':test'.
      at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
      at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:53)
      at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.addToTaskGraph(DefaultTaskExecutionPlan.java:99)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.addTasks(DefaultTaskGraphExecuter.java:74)
      at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:49)
      at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
      at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExecuter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:48)
      at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:46)
      at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
      at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExecuter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:48)
      at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:38)
      at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
      at org.gradle.execution.DefaultBuildExecuter.select(DefaultBuildExecuter.java:35)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:46)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.Main.main(Main.java:37)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
      at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:91)
      at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:192)
      at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:81)
      at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:69)
      at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
      at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency$TaskDependencyImpl.resolve(DefaultProjectDependency.java:164)
      at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:86)
      at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:200)
      at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
      at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
      at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:74)
      at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:63)
      ... 36 more

**Comment by prasenjeet86** [comment]
I am getting this issue while trying to run as per the steps given in url as Building from source code "https://github.com/ex3ndr/telegram-api" . I tried in many way but finally same issue is coming. Please help me to resolve this. I want to create a telegram Java client for desktop to integrate with my application.

Thanks in advance.

**Comment by jnitish25** [comment]
The project also depends on the actors folder. Copy telegram-actors to actors folder and then run the build file.

**Comment by prasenjeet86** [comment]
Hi Nitish,

I tried using actor folder also, facing same error. In case it works for yoy, can you please help me with the client or steps?

My mail id : prasenjeet86@gmail.com

Many thanks in advance.

Regards,
Peasenjeet

**Comment by pjr1060** [comment]
The gradle build files are out of date.  Here's what worked for me.
1. Clone all of the telegram-xxxx  projects into a colocated folder.
2. Go into telegram-api/ and edit build.gradle...  Add a repositories{} section shown here after apply plugin declarations (this fixes the android actors lib error)...

``` javascript
project.group = "org.telegram"

apply plugin: 'java'
apply plugin: 'shadow'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile project(':tl-core')
    compile project(':mtproto')
    compile project(':actors')
    compile files('libs/tl-api-v12.jar')
}
```
1.  Edit settings.gradle to the following, this fixes the project dependencies to the correct gradle cloned sub-projects (notice it assumes they are located as peers of the telegram-api/ folder)...

``` javascript
rootProject.name = "telegram-api"

include ':tl-core', ':mtproto', ':actors'

project(':tl-core').projectDir = new File( '../telegram-tl-core' )
project(':mtproto').projectDir = new File( '../telegram-mt' )
project(':actors').projectDir = new File( '../telegram-actors' )
```
1. You can now do **_gradle build**_  and it will build.  **_gradle shadowJar**_ will create a single deployable jar with all dependencies rolled up.

So now the next question is - why does the resulting snapshot shadow jar throw errors if I use it instead of the download 1.1.127 shadow jar?   **This project needs some TLC.**

Also where is the source for the lib/tl-api-v12.jar  ?

**Comment by kardapoltsev** [comment]
+1 for question about sources for the lib/tl-api-v12.jar
