### ISSUE TITLE
java.lang.SecurityException with Breaking context 4 time a second

### ISSUE THREAD

**Issue by alexkvak** [telegram-s/telegram-api-old#29]
Hi

when I deployed my app and suddenly became very often warnings and error from MTProto

```
WAR 17:39:11.907 r.m.b.c.t.logger.MTProtoLogger       MTProto#1005#Transport42106: Breaking context
WAR 17:39:11.934 r.m.b.c.t.logger.MTProtoLogger       MTProto#1002: Unsupported msgAuthKey
ERR 17:39:11.934 r.m.b.c.t.logger.MTProtoLogger       MTProto#1002#Transport42107
java.lang.SecurityException: null
    at org.telegram.mtproto.MTProto.decrypt(MTProto.java:540)
    at org.telegram.mtproto.MTProto.access$1900(MTProto.java:44) 
    at org.telegram.mtproto.MTProto$TcpListener.onRawMessage(MTProto.java:830) 
    at org.telegram.mtproto.transport.TcpContext.onMessage(TcpContext.java:167) 
    at org.telegram.mtproto.transport.TcpContext.access$1600(TcpContext.java:21) 
    at org.telegram.mtproto.transport.TcpContext$ReaderThread.run(TcpContext.java:320) 
```

but when I start app on my dev host I become 

```
ERR 10:02:24.035 r.m.b.c.t.logger.MTProtoLogger       MTProto#1002#Transport3 
java.io.IOException: null
    at org.telegram.mtproto.transport.TcpContext.readInt(TcpContext.java:586) 
    at org.telegram.mtproto.transport.TcpContext.access$700(TcpContext.java:21) 
    at org.telegram.mtproto.transport.TcpContext$ReaderThread.run(TcpContext.java:232) 
```

Should I ignore these messages?

**Comment by ashokcoolguys** [comment]
Have U fixed this??

am getting the below error frequently

java.io.IOException
    at org.telegram.mtproto.transport.TcpContext.readByte(TcpContext.java:627)
    at org.telegram.mtproto.transport.TcpContext.access$1400(TcpContext.java:21)
    at org.telegram.mtproto.transport.TcpContext$ReaderThread.run(TcpContext.java:284)

**Comment by alexkvak** [comment]
yes, I had issue with DC selection. You need first switch to the nearest DC, just after code verification
