### ISSUE TITLE
SNAPSHOT of telegram-api RuntimeException Unknown dispatcherId 'connection'

### ISSUE THREAD

**Issue by pjr1060** [telegram-s/telegram-api-old#31]
I managed to figure out how to build the telegram-api  shadowJar snapshot (see here for how to fix the gradle build files... https://github.com/ex3ndr/telegram-api/issues/26)

But if I replace 1.1.127 shadow jar with the snapshot build I see these errors...

``` javascript
Exception in thread "Connection#757386994" java.lang.RuntimeException: Unknown dispatcherId 'connection'
    at com.droidkit.actors.ActorSystem.actorOf(ActorSystem.java:102)
    at com.droidkit.actors.ActorSystem.actorOf(ActorSystem.java:63)
    at org.telegram.mtproto.transport.TransportTcpPool.<init>(TransportTcpPool.java:62)
    at org.telegram.mtproto.MTProto.<init>(MTProto.java:116)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:895)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:946)
```

And none of my (previously working) code will work.   What is the status of this project?  Please can you let us know if it is expected to work (for example with the telegram-bot example) and replaces the 1.1.127 release or is it unstable and expected to be broken like this?

Thanks - I'd really like to have a stable Java API to send messages into Telegram.

One final thing - if I call TelegramAPI.close()  with the 1.1.127 release it fails with NPE (so I can never cleanly shutdown) however if it do it with the SNAPSHOT it seems to work (but catch-22 I can't send message ;-)

**Comment by mcarrier69** [comment]
Did we ever get an update on this?  Pretty sure all Java Api is broken and wont work as of now, due to this bug.

**Comment by davidmartdom** [comment]
I think the status of this project is almost dead. The developer has left and we have his code working with Telegram API version #12.

Anyway I would use it if I had the certainty it's not going to stop working in the close future and with no way of upgrading in order to get work it again.

Conclusion: I don't really know if it's worthful to begin a project based in this java libraries.
