### ISSUE TITLE
NullPointerException at org.telegram.tl.StreamingUtils.writeTLObject(StreamingUtils.java:192)

### ISSUE THREAD

**Issue by gth9001** [telegram-s/telegram-api-old#34]
With great effor I builded working (almost) api library, and it even sent me sms code (I used telegram-bot code). But after I write this sms code I got the following exception:
`Exception in thread "Scheduller#1613213400" java.lang.NullPointerException
    at org.telegram.tl.StreamingUtils.writeTLObject(StreamingUtils.java:192)
    at org.telegram.api.requests.TLRequestMessagesSendMessage.serializeBody(Unknown Source) at org.telegram.api.requests.TLRequestMessagesSendMessage.serializeBody(Unknown Source)
    at org.telegram.tl.TLObject.serialize(TLObject.java:46)
    at org.telegram.tl.StreamingUtils.writeTLObject(StreamingUtils.java:192)
    at org.telegram.tl.StreamingUtils.writeTLMethod(StreamingUtils.java:203)
    at org.telegram.api.requests.TLRequestInvokeWithLayer11.serializeBody(Unknown Source)
    at org.telegram.tl.TLObject.serialize(TLObject.java:46)
    at org.telegram.tl.TLObject.serialize(TLObject.java:34)
    at org.telegram.mtproto.schedule.Scheduller.actualPackages(Scheduller.java:388)
    at org.telegram.mtproto.schedule.Scheduller.doSchedule(Scheduller.java:406)
    at org.telegram.mtproto.MTProto$SchedullerThread.run(MTProto.java:704)
    at org.telegram.api.requests.TLRequestMessagesSendMessage.serializeBody(Unknown Source)`
I think it can't serialize auth data. What can I do with it? Anybody faced the same problem? Thanks for answers.

**Comment by gth9001** [comment]
Problem solved :)

**Comment by danprat92** [comment]
@gth9001   Hey , i'm facing this issue , can u tell how did you solve it?

**Comment by gth9001** [comment]
@danprat92 Unfortunately I can't remember it now, it was a several months ago. But I can tell that finally I gave up on this library, there was too many problems
