### ISSUE TITLE
Error TimeoutException

### ISSUE THREAD

**Issue by alguienes** [telegram-s/telegram-api-old#54]
Buenas tardes, Alguien ha tenido este problema?

`
Exception in thread "Connection#1508177397" java.lang.NoClassDefFoundError: com/droidkit/actors/ActorCreator
    at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:895)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:946)
Caused by: java.lang.ClassNotFoundException: com.droidkit.actors.ActorCreator
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 2 more
Exception in thread "main" org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:369)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:428)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:420)
    at main.Application.login(Application.java:386)
    at main.Application.main(Application.java:45)
`

No he podido solucionarlo, si alguien lo ha solucionado le agradecería que me ayudara.

**Comment by yasserzamani** [comment]
It also cannot find `com.droidkit.actors.ActorCreator` class.

**Comment by yasserzamani** [comment]
Please do not continue as  this library is very old according to [this so question - Telegram Api layer 52, super groups and channels](http://stackoverflow.com/questions/38801700/telegram-api-layer-52-super-groups-and-channels) which says:

> i am java developer . i found telegram java api in github .but this api is old . i want to make new library for java (support channels and superGroups)
